version: '3'

services:
  nginx:
    image: pitchanai/sertis-nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    container_name: "sertis-nginx"
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Bangkok      
    extra_hosts:
      - "sertis-dev.pitchanai.com:127.0.0.1"